"""PROBLEM STATEMENT:-WRITE A PYTHON PROGRAM TO COMPUTE FOLLOWING OPERATIONS ON STRING 
1)TO DISPLAY WORD WITH THE LONGEST LENGTH 
2)TO DETERMINE THE FREQUENCY OF OCCURRENCE OF PARTICULAR CHARACTER IN STRING
3)TO CHECK WHETHER STRING IS PALINDROME OR  NOT 
4)TO DISPLAY INDEX OF THE FIRST APPEARANCE OF THE SUBSTRING
5)TO COUNT THE OCCURRENCES OF EACH WORD IN THE GIVEN STRING"""

a=str(input("ENTER THE STRING:\t"))

def lword():  
	
	longest = max(a.split(),key=len)
	print("LONGEST WORD IS ",longest,"WITH LENGTH",len(longest))
	
def freq():		
	
	char = input("PLEASE ENTER THE CHAR TO FIND FREQUENCY OF THE CHARACTER\t")
	count = 0
	for i in range(len(a)) :
		if (a[i] == char) :
			count = count + 1
	print("THE FREQUENCY OF ", char, "IN THE ",a,"IS: ", count)

def pal():	
	
	if(a==a[::-1]) :
		print("STRING IS PALINDROME")
	else :
		print("STRING IS NOT PALINDROME")

def sindex():			
	
	sub = str(input("ENTER WORD TO CHECK FOR APPERANCE :"))
	print("INDEX OF FIRST APPEARANCE OF THE SUBSTRING " + sub+ " IS")
	print(a.find(sub))

	if (a.find(sub) == -1) :
		print("SUBSTRING NOT FOUND")
	else :
		print("SUBSTRING FOUND")

def wfreq():	
	freq = {}
	for i in a :
		if (i in freq) :
			freq[i] += 1
		else :
			freq[i] = 1
	print("Count of all characters in sentence is :\n "
			 + str(freq))

main=1
while main==1:
	print("\n1.TO DISPLAY WORD WITH THE LONGEST LENGTH ")
	print("2.TO DETERMINE THE FREQUENCY OF OCCURRENCE OF PARTICULAR CHARACTER IN STRING ")
	print("3.TO CHECK WHETHER STRING IS PALINDROME OR NOT ")
	print("4.TO DISPLAY INDEX OF THE FIRST APPEARANCE OF THE SUBSTRING ")
	print("5.TO COUNT THE OCCURRENCES OF EACH WORD IN THE GIVEN STRING ")
	print("6.QUIT\n")
	
	
	ch=int(input("ENTER YOUR CHOICE\n"))

	if(ch==1):
		lword()
	elif (ch==2):
		freq()
	elif (ch==3):
		pal()
	elif (ch==4):
		sindex()
	elif (ch==5):
		wfreq()
	elif(ch==6):
		print("THANK YOU ")
		quit()
	else:
		print("ENTER A VALID CHOICE")
		
'''output
ENTER THE STRING:	INDIA IS MY COUNTRY

1.TO DISPLAY WORD WITH THE LONGEST LENGTH 
2.TO DETERMINE THE FREQUENCY OF OCCURRENCE OF PARTICULAR CHARACTER IN STRING 
3.TO CHECK WHETHER STRING IS PALINDROME OR NOT 
4.TO DISPLAY INDEX OF THE FIRST APPEARANCE OF THE SUBSTRING 
5.TO COUNT THE OCCURRENCES OF EACH WORD IN THE GIVEN STRING 
6.QUIT

ENTER YOUR CHOICE
1
LONGEST WORD IS  COUNTRY WITH LENGTH 7

1.TO DISPLAY WORD WITH THE LONGEST LENGTH 
2.TO DETERMINE THE FREQUENCY OF OCCURRENCE OF PARTICULAR CHARACTER IN STRING 
3.TO CHECK WHETHER STRING IS PALINDROME OR NOT 
4.TO DISPLAY INDEX OF THE FIRST APPEARANCE OF THE SUBSTRING 
5.TO COUNT THE OCCURRENCES OF EACH WORD IN THE GIVEN STRING 
6.QUIT

ENTER YOUR CHOICE
2
PLEASE ENTER THE CHAR TO FIND FREQUENCY OF THE CHARACTER	T
THE FREQUENCY OF  T IN THE  INDIA IS MY COUNTRY IS:  1

1.TO DISPLAY WORD WITH THE LONGEST LENGTH 
2.TO DETERMINE THE FREQUENCY OF OCCURRENCE OF PARTICULAR CHARACTER IN STRING 
3.TO CHECK WHETHER STRING IS PALINDROME OR NOT 
4.TO DISPLAY INDEX OF THE FIRST APPEARANCE OF THE SUBSTRING 
5.TO COUNT THE OCCURRENCES OF EACH WORD IN THE GIVEN STRING 
6.QUIT

ENTER YOUR CHOICE
3
STRING IS NOT PALINDROME

1.TO DISPLAY WORD WITH THE LONGEST LENGTH 
2.TO DETERMINE THE FREQUENCY OF OCCURRENCE OF PARTICULAR CHARACTER IN STRING 
3.TO CHECK WHETHER STRING IS PALINDROME OR NOT 
4.TO DISPLAY INDEX OF THE FIRST APPEARANCE OF THE SUBSTRING 
5.TO COUNT THE OCCURRENCES OF EACH WORD IN THE GIVEN STRING 
6.QUIT

ENTER YOUR CHOICE
4
ENTER WORD TO CHECK FOR APPERANCE :MY
INDEX OF FIRST APPEARANCE OF THE SUBSTRING MY IS
9
SUBSTRING FOUND

1.TO DISPLAY WORD WITH THE LONGEST LENGTH 
2.TO DETERMINE THE FREQUENCY OF OCCURRENCE OF PARTICULAR CHARACTER IN STRING 
3.TO CHECK WHETHER STRING IS PALINDROME OR NOT 
4.TO DISPLAY INDEX OF THE FIRST APPEARANCE OF THE SUBSTRING 
5.TO COUNT THE OCCURRENCES OF EACH WORD IN THE GIVEN STRING 
6.QUIT

ENTER YOUR CHOICE
5
Count of all characters in sentence is :
 {'T': 1, 'A': 1, 'O': 1, 'S': 1, 'D': 1, 'C': 1, 'N': 2, 'M': 1, 'U': 1, 'I': 3, 'Y': 2, 'R': 1, ' ': 3}

1.TO DISPLAY WORD WITH THE LONGEST LENGTH 
2.TO DETERMINE THE FREQUENCY OF OCCURRENCE OF PARTICULAR CHARACTER IN STRING 
3.TO CHECK WHETHER STRING IS PALINDROME OR NOT 
4.TO DISPLAY INDEX OF THE FIRST APPEARANCE OF THE SUBSTRING 
5.TO COUNT THE OCCURRENCES OF EACH WORD IN THE GIVEN STRING 
6.QUIT

ENTER YOUR CHOICE
6
THANK YOU 


'''
